import assert from "node:assert/strict";
import fs from "node:fs";

const stateApi = fs.readFileSync(new URL("../api/state.php", import.meta.url), "utf8");
const smsApi = fs.readFileSync(new URL("../api/sms-settings.php", import.meta.url), "utf8");
const revenueApi = fs.readFileSync(new URL("../api/revenue-list.php", import.meta.url), "utf8");
const voucherApi = fs.readFileSync(new URL("../api/voucher-list.php", import.meta.url), "utf8");
const groupSummaryApi = fs.readFileSync(new URL("../api/group-summary.php", import.meta.url), "utf8");
const giftCardApi = fs.readFileSync(new URL("../api/gift-card-list.php", import.meta.url), "utf8");
const customerDetailApi = fs.readFileSync(new URL("../api/customer-detail.php", import.meta.url), "utf8");
const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");

assert.match(stateApi, /assert_sections_readable_by_user\(\$requestedSections, \$user\)/, "State reads must enforce role permissions on the server");
assert.match(stateApi, /if \(\$keys === \[\]\)[\s\S]*бүх мэдээллийг нэг дор татах боломжгүй/, "Branch accounts must never use the legacy full-state read");
assert.match(stateApi, /\$allowed = \[[\s\S]*'giftCards'/, "Branch state reads must use a positive section allowlist");
assert.match(stateApi, /\$copy\['serviceHistory'\] = \$scopedHistory/, "Branch report payloads must strip other branches' customer history");
assert.match(stateApi, /'voucherLogs'.*'performanceStatements'/s, "Branch payloads must scope voucher and performance rows on the server");
assert.match(smsApi, /\$user = require_admin\(\)/, "SMS settings and history must be admin-only");
assert.match(smsApi, /\$pageSize = 100/, "SMS history must stay server-paginated");
assert.match(revenueApi, /\$pageSize = min\(100, max\(10,/, "Revenue rows must be server-paginated");
assert.match(revenueApi, /\(\$user\['role'\] \?\? ''\) === 'salon'/, "Revenue must enforce salon scope on the server");
assert.match(voucherApi, /\$pageSize = min\(100, max\(10,/, "Voucher history must be server-paginated");
assert.match(voucherApi, /\$user = require_auth\(\)/, "Voucher history must remain limited to authenticated accounts");
assert.doesNotMatch(voucherApi, /\$salon = \(\$user\['role'\]/, "Voucher history is global and must not be restricted to one branch");
assert.match(voucherApi, /section_key IN \('voucherLogs','voucherRoles','customers'\)/, "Voucher history must rebuild its read model from authoritative customer payments");
assert.match(voucherApi, /\$paymentItem\['method'\][\s\S]*\['voucher', 'ваучер'\]/, "Voucher history must recover voucher payments even when the legacy log section is empty");
assert.match(groupSummaryApi, /require_admin\(\)/, "Group summary must remain admin-only");
assert.match(giftCardApi, /\$pageSize = min\(100, max\(10,/, "Gift cards must be server-paginated");
assert.match(giftCardApi, /\$user = require_auth\(\)/, "Gift-card browsing must remain limited to authenticated accounts");
assert.doesNotMatch(giftCardApi, /\$user\['role'\].*=== 'salon'/s, "Branch accounts must be able to browse the global gift-card directory");
assert.match(customerDetailApi, /\$registeredSalon !== \$salon.*\$queueSalon !== \$salon.*!\$hasSalonHistory/s, "Customer detail must enforce branch relationship on the server");
assert.match(app, /revenue-list\.php\?/, "Revenue UI must use the server-side filtered endpoint");
assert.match(app, /voucher-list\.php\?/, "Voucher history UI must use the server-side filtered endpoint");
assert.match(app, /function voucherDirectoryQuery\(\)[\s\S]*pageSize: "100"/, "Voucher history must request one hundred rows per page");
assert.doesNotMatch(app, /function voucherDirectoryQuery\(\)[\s\S]*?currentMonthDateRange\(\)[\s\S]*?async function loadVoucherDirectory/, "Voucher history must show the newest global rows before a date filter is submitted");
assert.match(app, /vouchers: \["voucherRoles"\]/, "Opening vouchers must not download every historical voucher row");
assert.match(app, /Voucher history is a paged read model[\s\S]*vouchers: \["voucherRoles"\]/, "Voucher page must never write a paged history back as the full section");
assert.match(app, /eligibilityChanged \? \["voucherRoles", "pricePolicy"\] : \["voucherRoles"\]/, "Ordinary voucher-role saves must not write an unloaded pricing policy");
assert.match(app, /eligibilityChanged[\s\S]*loadedServerSections\.has\("pricePolicy"\)[\s\S]*synchronizeServerState\(null, \["pricePolicy"\]/, "Cashier eligibility changes must load pricing policy before saving it");
assert.match(app, /voucherLog = \{[\s\S]*salon: historyItem\.salon \|\| historyItem\.branch \|\| activeAccount\.salon/, "New voucher usage rows must carry their branch ownership");
assert.match(app, /groups: \["customerTypes", "customerTypeRules", "pricePolicy"\]/, "Opening groups must not download all customer history");
assert.match(app, /group-summary\.php/, "Group counts must come from a lightweight server summary");
assert.match(app, /giftCards: \["generalSettings"\]/, "Opening gift cards must not download the full section");
assert.match(app, /gift-card-list\.php\?/, "Gift card browsing must use the paged endpoint");
assert.match(app, /function giftCardDirectoryQuery\(\)[\s\S]*pageSize: "100"/, "Gift cards must request one hundred rows per page");
assert.match(stateApi, /function merge_salon_sections[\s\S]*foreach \(\['bookings',[\s\S]*'voucherLogs',[\s\S]*\] as \$section\)/, "Branch voucher writes must merge only their owned rows instead of replacing the global history");
assert.match(app, /ensureGiftCardDirectorySections\(\)/, "Gift card mutations must first load the authoritative full section");
assert.match(app, /performance: \["salons", "generalSettings"\]/, "Opening revenue must not download all customer history");
assert.match(app, /settingsUsers: \["salons"\]/, "User settings must not download audit history");
assert.match(app, /branches: \["salons", "homepageSettings"\]/, "Branch settings must not download bookings");
assert.match(app, /settingsPricing: \["pricePolicy", "voucherRoles", "customerTypes", "customerTypeRules"\]/, "Pricing must not fetch or save every customer until recalculation is explicitly requested");
assert.match(app, /settingsUsers: \[\]/, "User changes must not write a browser copy of audit history");

console.log("role-scope-and-revenue.test: OK");
